export const ADD_DATA_START = 'ADD_DATA_START';
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS';
export const ADD_DATA_FAIL = 'ADD_DATA_FAIL';
export const ADD_DATA_INIT = 'ADD_DATA_INIT';


export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
export const SEARCH_DATA = 'SEARCH_DATA';


export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';